library(babeldown)
deepl_usage()

# Chapters
# deepl_translate("index.Rmd", "index-pl.Rmd", source_lang = "EN", target_lang = "PL")
# deepl_translate("01-introduction.Rmd", "01-introduction-pl.Rmd", source_lang = "EN", target_lang = "PL")
deepl_translate("02-spatial-data.Rmd", "02-spatial-data-pl.Rmd", source_lang = "EN", target_lang = "PL")
# deepl_translate("03-attribute-operations.Rmd", "03-attribute-operations-pl.Rmd", source_lang = "EN", target_lang = "PL")
# deepl_translate("04-spatial-operations.Rmd", "04-spatial-operations-pl.Rmd", source_lang = "EN", target_lang = "PL")
# deepl_translate("05-geometry-operations.Rmd", "05-geometry-operations-pl.Rmd", source_lang = "EN", target_lang = "PL")
# deepl_translate("06-raster-vector.Rmd", "06-raster-vector-pl.Rmd", source_lang = "EN", target_lang = "PL")
# deepl_translate("07-reproj.Rmd", "07-reproj-pl.Rmd", source_lang = "EN", target_lang = "PL")
# deepl_translate("08-read-write-plot.Rmd", "08-read-write-plot-pl.Rmd", source_lang = "EN", target_lang = "PL")
deepl_translate("09-mapping.Rmd", "09-mapping-pl.Rmd", source_lang = "EN", target_lang = "PL")
deepl_translate("10-gis.Rmd", "10-gis-pl.Rmd", source_lang = "EN", target_lang = "PL")
deepl_translate("11-algorithms.Rmd", "11-algorithms-pl.Rmd", source_lang = "EN", target_lang = "PL")
deepl_translate("12-spatial-cv.Rmd", "12-spatial-cv-pl.Rmd", source_lang = "EN", target_lang = "PL")
deepl_translate("13-transport.Rmd", "13-transport-pl.Rmd", source_lang = "EN", target_lang = "PL")
deepl_translate("14-location.Rmd", "14-location-pl.Rmd", source_lang = "EN", target_lang = "PL")
deepl_translate("15-eco.Rmd", "15-eco-pl.Rmd", source_lang = "EN", target_lang = "PL")
deepl_translate("16-synthesis.Rmd", "16-synthesis-pl.Rmd", source_lang = "EN", target_lang = "PL")

# Exercises
deepl_translate("_01-ex.Rmd", "_01-ex-pl.Rmd", source_lang = "EN", target_lang = "PL")
deepl_translate("_02-ex.Rmd", "_02-ex-pl.Rmd", source_lang = "EN", target_lang = "PL")
deepl_translate("_03-ex.Rmd", "_03-ex-pl.Rmd", source_lang = "EN", target_lang = "PL")
deepl_translate("_04-ex.Rmd", "_04-ex-pl.Rmd", source_lang = "EN", target_lang = "PL")
deepl_translate("_05-ex.Rmd", "_05-ex-pl.Rmd", source_lang = "EN", target_lang = "PL")
deepl_translate("_06-ex.Rmd", "_06-ex-pl.Rmd", source_lang = "EN", target_lang = "PL")
deepl_translate("_07-ex.Rmd", "_07-ex-pl.Rmd", source_lang = "EN", target_lang = "PL")
deepl_translate("_08-ex.Rmd", "_08-ex-pl.Rmd", source_lang = "EN", target_lang = "PL")
deepl_translate("_09-ex.Rmd", "_09-ex-pl.Rmd", source_lang = "EN", target_lang = "PL")
deepl_translate("_10-ex.Rmd", "_10-ex-pl.Rmd", source_lang = "EN", target_lang = "PL")
deepl_translate("_11-ex.Rmd", "_11-ex-pl.Rmd", source_lang = "EN", target_lang = "PL")
deepl_translate("_12-ex.Rmd", "_12-ex-pl.Rmd", source_lang = "EN", target_lang = "PL")
deepl_translate("_13-ex.Rmd", "_13-ex-pl.Rmd", source_lang = "EN", target_lang = "PL")
deepl_translate("_14-ex.Rmd", "_14-ex-pl.Rmd", source_lang = "EN", target_lang = "PL")
deepl_translate("_15-ex.Rmd", "_15-ex-pl.Rmd", source_lang = "EN", target_lang = "PL")